spring.application.name=flexspace
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never

# JWT Configuration
jwt.secret=b3bcd9ec1b965ed25116eb8ebb10f1cf2d7be741bf40e00734e0992ef099c169
jwt.expiration=86400000

# Console level
logging.level.root=INFO

# File logging
logging.file.name=logs/app.log

# Optional: cleaner format
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger - %msg%n